name: CCC CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/google-services.json

      - name: Decode Common Secrets
        env:
          COMMON_SECRETS: ${{ secrets.COMMON_SECRETS }}
        run: echo $COMMON_SECRETS > common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/secret/Secrets.kt

      - name: Gradle Build
        run: ./gradlew build --parallel

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Xcode build
        run: xcodebuild build -project ios/ios.xcodeproj/ -sdk iphonesimulator -destination "OS=14.0" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO EXCLUDED_ARCHS=arm64

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ccc
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ccc
          status: FAILED
          color: danger