name: CCC CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/google-services.json

      - name: Decode Keys
        env:
          KEYS: ${{ secrets.KEYS }}
        run: mkdir common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/key; echo $KEYS > common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/key/Keys.kt

      - name: Gradle Build
        run: ./gradlew build --parallel

#      https://github.com/CocoaPods/CocoaPods/issues/10065
#      todo it is broken after cocoapod integration no workaround found yet
#      - name: Set up Xcode
#        uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: latest
#
#      - name: Install Cocoapods
#        run: cd ios/CCC; gem install cocoapods; pod repo update; pod setup; pod install
#
#      - name: Xcode build
#        run: xcodebuild build -workspace ios/CCC.xcworkspace -scheme CCC -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ccc
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ccc
          status: FAILED
          color: danger